apiVersion: challenge.kubeasy.dev/v1alpha1
kind: StaticValidation
metadata:
  name: check-network-policy
spec:
  target:
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    labelSelector:
      matchExpressions:
        - key: validate
          operator: NotIn
          values:
            - "false"
  rulesConfigMap:
    name: rego-rules-partial-outage