apiVersion: v1
kind: ConfigMap
metadata:
  name: rego-rules-partial-outage
data:
  allow-to-backend.rego: |
    package kubeasy.challenge

    violation[{"msg": msg}] {
        not allows_frontend_to_backend(input)
        msg := "You must allow pods with label app=frontend to access pods with app=backend on port 5678"
      }

      allows_frontend_to_backend(np) {
        np.spec.podSelector.matchLabels.app == "backend"
        some i
        np.spec.ingress[i].from[_].podSelector.matchLabels.app == "frontend"
        np.spec.ingress[i].ports[_].port == 5678
      }