apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: protect-deny-all-networkpolicy
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: block-delete-deny-all
      match:
        any:
          - resources:
              kinds:
                - NetworkPolicy
              names:
                - deny-all
              operations:
                - DELETE
      validate:
        message: "Deleting the deny-all NetworkPolicy is not allowed. Add ingress rules instead."
        deny: {}
