apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: avoid-deny-delete-networkpolicy
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  validationFailureAction: enforce
  rules:
    - name: block-delete-deny-all
      match:
        resources:
          kinds: ["NetworkPolicy"]
          names: ["deny-all"]
      validate:
        message: "You are not allowed to delete the default NetworkPolicy"
        deny: {}