apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: restrict-job-modifications
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: preserve-schedule
      match:
        resources:
          kinds: ["CronJob"]
          names: ["data-processor"]
      validate:
        message: "CronJob schedule must not be modified"
        pattern:
          spec:
            schedule: "0 2 * * *"

    - name: preserve-processing-logic
      match:
        resources:
          kinds: ["CronJob"]
          names: ["data-processor"]
      validate:
        message: "Processing container image must remain busybox:latest"
        pattern:
          spec:
            jobTemplate:
              spec:
                template:
                  spec:
                    containers:
                      - name: "processor"
                        image: "busybox:latest"