apiVersion: v1
kind: ConfigMap
metadata:
  name: check-statefulset
data:
  check-replicas-count.rego: |
    package kubeasy.challenge

    violation[{"msg": msg}] {
      input.kind == "StatefulSet"
      input.spec.replicas == 1
      msg := "StatefulSet should have replicas set to 1 for ReadWriteOnce volumes"
    }
