apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
        version: v1
    spec:
      containers:
        - name: api
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: http
          env:
            - name: SERVICE_NAME
              value: "api-service"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /healthz  # Problem: nginx doesn't have /healthz endpoint
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /  # This works fine
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
