apiVersion: challenge.kubeasy.dev/v1alpha1
kind: DynamicValidation
metadata:
  name: service-connectivity
spec:
  target:
    apiVersion: v1
    kind: Service
    name: api-service
  checks:
    - kind: endpoints
      endpointCheck:
        serviceName: "api-service"
        expectedEndpoints: 2
    - kind: ingress
      ingressCheck:
        ingressName: "api-ingress"
        expectedBackend: "api-service"