apiVersion: challenge.kubeasy.dev/v1alpha1
kind: StaticValidation
metadata:
  name: validate-role
spec:
  target:
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    name: startup-check-role
  rulesConfigMap:
    name: rego-rules-role