apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: postgres-db
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
