name: 🆘 Help & Support
description: Get help with challenges, setup, or usage questions
title: "[Help]: "
labels: ["help", "question"]
assignees:
  - kubeasy-dev
body:
  - type: markdown
    attributes:
      value: |
        Need help? We're here to assist! Please provide as much detail as possible so we can help you effectively.

  - type: dropdown
    id: help-type
    attributes:
      label: Type of Help Needed
      description: What kind of help do you need?
      options:
        - Challenge setup/configuration
        - Understanding challenge requirements
        - Kubernetes deployment issues
        - Troubleshooting errors
        - Best practices guidance
        - General usage questions
        - Other
    validations:
      required: true

  - type: input
    id: challenge-name
    attributes:
      label: Challenge Name
      description: If your question is about a specific challenge, please specify which one
      placeholder: e.g., access-pending, partial-outage, probes-drift
    validations:
      required: false

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe what you need help with
      placeholder: Be as specific as possible about what you're trying to achieve or what's not working
    validations:
      required: true

  - type: textarea
    id: what-tried
    attributes:
      label: What Have You Tried?
      description: Please describe what you've already attempted
      placeholder: |
        - Read the documentation
        - Searched existing issues
        - Tried solution X but got error Y
        - etc.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide details about your environment
      placeholder: |
        - OS: [e.g., macOS, Ubuntu, Windows]
        - Kubernetes version: [e.g., 1.28.2]
        - kubectl version: [e.g., 1.28.2]
        - Cluster type: [e.g., minikube, kind, EKS, GKE, AKS]
    validations:
      required: false

  - type: textarea
    id: error-output
    attributes:
      label: Error Output/Logs
      description: If you're getting errors, please paste the relevant output
      render: shell
    validations:
      required: false

  - type: textarea
    id: current-config
    attributes:
      label: Current Configuration
      description: Please share relevant configuration files or commands you're using
      render: yaml
    validations:
      required: false

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this for you?
      options:
        - Low (can wait)
        - Medium (would like help soon)
        - High (blocking my progress)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context that might be helpful
      placeholder: Screenshots, related issues, or any other relevant information
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I have read the documentation and checked existing issues
          required: true
        - label: I have provided enough context for someone to help me
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true
