apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: protect-web-app
  namespace: healthy-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: preserve-container-image
      match:
        resources:
          kinds: ["Deployment"]
          names: ["web-app"]
      validate:
        message: "Cannot change the container image - configure health probes instead"
        pattern:
          spec:
            template:
              spec:
                containers:
                  - name: app
                    image: "hashicorp/http-echo:0.2.3"
