apiVersion: v1
kind: ConfigMap
metadata:
  name: check-deployment
data:
  liveness-present.rego: |
    package kubeasy.challenge

    violation[{"msg": msg}] {
      container := input.spec.template.spec.containers[_]
      not container.livenessProbe
      msg := "Liveness probe is missing"
    }
  readiness-present.rego: |
    package kubeasy.challenge

    violation[{"msg": msg}] {
      container := input.spec.template.spec.containers[_]
      not container.readinessProbe
      msg := "Readiness probe is missing"
    }