apiVersion: v1
kind: ConfigMap
metadata:
  name: check-deployment
data:
  liveness-present.rego: |
    package kubeasy.challenge

    violation[{"msg": msg}] {
      some i
      not input.spec.template.spec.containers[i].livenessProbe
      msg := "Liveness probe is missing"
    }
  readiness-present.rego: |
    package kubeasy.challenge

    violation[{"msg": msg}] {
      some i
      not input.spec.template.spec.containers[i].readinessProbe
      msg := "Readiness probe is missing"
    }