apiVersion: v1
kind: ConfigMap
metadata:
  name: check-deployment
data:
  startup-probe-present.rego: |
    package kubeasy.challenge

    violation[{"msg": msg}] {
      container := input.spec.template.spec.containers[_]
      not container.startupProbe
      msg := "Startup probe is required for slow-starting applications"
    }

  readiness-initial-delay.rego: |
    package kubeasy.challenge

    violation[{"msg": msg}] {
      container := input.spec.template.spec.containers[_]
      container.readinessProbe
      container.readinessProbe.initialDelaySeconds < 15
      msg := "Readiness probe initialDelaySeconds should be at least 15 seconds for slow-starting apps"
    }