apiVersion: challenge.kubeasy.dev/v1alpha1
kind: LogValidation
metadata:
  name: database-connection-check
spec:
  target:
    kind: Pod
    labelSelector:
      matchLabels:
        app: api-service
  expectedStrings:
    - "Connected to database successfully"
  sinceSeconds: 120
