# This ConfigMap represents a configuration update that was applied
# The ops team updated the cache setting to true, but the pods are still running
# with the old configuration because there's no mechanism to trigger a rollout

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  config.json: |
    {
      "database": {
        "host": "db.default.svc.cluster.local",
        "port": 5432,
        "name": "production"
      },
      "server": {
        "port": 8080,
        "host": "0.0.0.0"
      },
      "features": {
        "cache": true,
        "analytics": true,
        "debug": false
      }
    }
