apiVersion: challenge.kubeasy.dev/v1alpha1
kind: StaticValidation
metadata:
  name: validate-pod-nginx
spec:
  target:
    apiVersion: v1
    kind: Pod
    labelSelector:
      matchLabels:
        app: nginx
  rulesConfigMap:
    name: rego-rules-nginx