apiVersion: v1
kind: ConfigMap
metadata:
  name: check-probes
data:
  readiness-probe-path.rego: |
    package kubeasy.challenge

    violation[{"msg": msg}] {
      container := input.spec.template.spec.containers[_]
      container.readinessProbe
      container.readinessProbe.httpGet
      container.readinessProbe.httpGet.path == "/"
      msg := "Readiness probe path should be / for nginx (not /healthz)"
    }
