apiVersion: challenge.kubeasy.dev/v1alpha1
kind: DynamicValidation
metadata:
  name: postgres-running
spec:
  target:
    apiVersion: v1
    kind: Pod
    labelSelector:
      matchLabels:
        app: postgres
  checks:
    - kind: status
      statusCheck:
        condition: "Ready"
        expectedStatus: "True"
    - kind: volume
      volumeCheck:
        pvcName: "postgres-data"
        expectedStatus: "Bound"