apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-validation
data:
  json-syntax.rego: |
    package kubeasy.challenge

    violation[{"msg": msg}] {
      input.kind == "ConfigMap"
      input.metadata.name == "app-config"
      config_data := input.data["config.json"]
      # Check for missing comma after localhost
      contains(config_data, "\"localhost\"\n")
      msg := "Configuration syntax appears to be invalid"
    }