on:
  push:
    branches:
      - main
    paths:
      - '**/image/**'
      - '.github/workflows/publish-images.yaml'

name: Build and Publish Docker Images

permissions:
  packages: write
  contents: read

env:
  IMAGE_ROOT: ghcr.io/kubeasy-dev/
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  images:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.get_images.outputs.images }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Get all subdirectories wiich contains image folder
        id: get_images
        run: |
          echo images=$(find . -type d -name "image" -exec dirname {} \; | sed 's|^\./||g' | jq -R . | jq -sc .) >> "$GITHUB_OUTPUT"
      - name: Debug
        run: |
          echo "Images found: ${{ steps.get_images.outputs.images }}"

  build-and-push:
    runs-on: ubuntu-latest
    needs: images
    strategy:
      matrix:
        image: ${{ fromJson(needs.images.outputs.images) }} 
    steps: 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
          platforms: ${{ env.PLATFORMS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ env.PLATFORMS }}
          context: ${{ matrix.image }}/image
          file: ${{ matrix.image }}/image/Dockerfile
          push: true
          tags: ${{ env.IMAGE_ROOT }}${{ matrix.image }}/latest
          cache-from: type=gha
          cache-to: type=gha, mode=max